export const appStatesConstants = {
    SET_SELECTED_COLECTIVOS: 'SET_SELECTED_COLECTIVOS',
    SET_SELECTED_COLECTIVO: 'SET_SELECTED_COLECTIVO',
    SET_SELECTED_CARGOS: 'SET_SELECTED_CARGOS',
    SET_STEPPER_CURRENT: 'SET_STEPPER_CURRENT',
    // SEARCH_CONTACTO_SET: 'SEARCH_CONTACTO_SET',
}

