export const appStatesConstants = {
    SET_MULTI_COLECTIVO: 'SET_MULTI_COLECTIVO',
    SET_CARGO: 'SET_CARGO',
    SET_STEPPER_CURRENT: 'SET_STEPPER_CURRENT',
    // SEARCH_CONTACTO_SET: 'SEARCH_CONTACTO_SET',
}    

