export const cargoConstants = {
    CARGO_GET_ALL: 'CARGO_GET_ALL',
    CARGO_SUCCESS: 'CARGO_SUCCESS',
    CARGO_ERROR: 'CARGO_ERROR',
    CARGO_GET_PAGE: 'CARGO_GET_PAGE',
    CARGO_SEARCH: 'CARGO_SEARCH',
}
