export const colectivoConstants = {
    COLECTIVO_GET_ALL: 'COLECTIVOS_GET_ALL',
    COLECTIVO_GET_ONE: 'COLECTIVOS_GET_ONE',
    COLECTIVO_UPDATE: 'COLECTIVO_UPDATE',
    COLECTIVO_CREATE: 'COLECTIVO_CREATE',
    COLECTIVO_DELETE: 'COLECTIVO_DELETE',
    COLECTIVO_SUCCESS: 'COLECTIVO_SUCCESS',
    COLECTIVO_ERROR: 'COLECTIVO_ERROR',
}
