export const colectivoConstants = {
    COLECTIVO_GET_ALL: 'COLECTIVOS_GET_ALL',
    COLECTIVO_GET_ONE: 'COLECTIVOS_GET_ONE',
    COLECTIVO_SUCCESS: 'COLECTIVO_SUCCESS',
    COLECTIVO_ERROR: 'COLECTIVO_ERROR',
}
