export const selectionsConstants = {
    SELECTED_PAIS_SET: 'SELECTED_PAIS_SET',
    SELECTED_COLECTIVO_SET: 'SELECTED_COLECTIVO_SET',
    SELECTED_CARGO_SET: 'SELECTED_CARGO_SET',
    // SEARCH_CONTACTO_SET: 'SEARCH_CONTACTO_SET',
}    

