export const selectionsConstants = {
    SET_TRATAMIENTO: 'SET_TRATAMIENTO',
    SET_PAIS: 'PAIS_SET',
    SET_MULTI_COLECTIVO: 'SET_MULTI_COLECTIVO',
    SET_SINGLE_COLECTIVO: 'SET_SINGLE_COLECTIVO',
    SET_SUBCOLECTIVO: 'SET_SUBCOLECTIVO',
    SET_CARGO: 'SET_CARGO',
    // SEARCH_CONTACTO_SET: 'SEARCH_CONTACTO_SET',
}    

