export const selectionsConstants = {
    SELECTED_PAIS_SET: 'SELECTED_PAIS_SET',
    SET_MULTI_COLECTIVO: 'SET_MULTI_COLECTIVO',
    SET_SINGLE_COLECTIVO: 'SET_SINGLE_COLECTIVO',
    SELECTED_CARGO_SET: 'SELECTED_CARGO_SET',
    // SEARCH_CONTACTO_SET: 'SEARCH_CONTACTO_SET',
}    

