export const subColectivoConstants = {
    SUBCOLECTIVO_GET_FROM_COLECTIVO: 'SUBCOLECTIVOS_GET_FROM_COLECITVO',
    SUBCOLECTIVO_SUCCESS: 'SUBCOLECTIVO_SUCCESS',
    SUBCOLECTIVO_ERROR: 'SUBCOLECTIVO_ERROR',
}
